version: 0.2

#env: 
  #parameter-store:
    # CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
    #dbhost: vprofile-rds-prod.cxxeobi4lvqr.us-east-1.rds.amazonaws.com
    #dbuser: admin
    #dbpass: V43JF6iIxwS2Blng0xvY
   

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq 
      - wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.5.4/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
      - sed -i "s/jdbc.password=admin123/jdbc.password=V43JF6iIxwS2Blng0xvY/" src/main/resources/application.properties
      - sed -i "s/jdbc.username=admin/jdbc.username=admin/" src/main/resources/application.properties
      - sed -i "s/db01:3306/vprofile-rds-prod.cxxeobi4lvqr.us-east-1.rds.amazonaws.com:3306/" src/main/resources/application.properties   
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - mvn package
artifacts:
  files:
     - '**/*'
  base-directory: 'target/vprofile-v2'
